services:
  - type: web
    name: wachitraductor-api
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: node dist/main.js
    envVars:
      - key: NODE_ENV
        value: production
